### PR TITLE
Add height above ground and activity information

### PR DESCRIPTION
**Pull request by stefwalter**
Adds height above ground information using the HGT library and data. And shows the assumed activity based on that, including the "concern" activity for nodes that may be in a position where they are at risk.

See Issue #63 

 * [x] Add unit tests for HGT
 * [x] Show AGL in "Show Details"

### CODE REVIEW

**Comment by stefwalter** [comment]
@ketan I think it may be worth storing the high above ground information along side the altitude information in the database, as part of a Position object. This is because it would allow other tools (beyond just the map), such as automated scripts, or alerts to consume that information (in the future). 

WDYT?

**Comment by ketan** [comment]
Doable. However, to be honest - I have not given it much thought yet. It does make sense to save AGL in a column, next to the altitude, makes it easy to see that the AGL height is either static, or within some close threshold from the ground level.

**Review by ketan — COMMENTED** [review]
Looks good. I'll wait for the PR to complete. But a couple of observations (or opinions, depending on your PoV):

The default value of `0` in the DTO seems odd. Since the column is nullable, perhaps set to null to indicate that the height is not available.

`0` could be interpreted to mean that the pilot has landed :)

Please add some unit tests for the AGL logic. Maybe add a few known points and assert that the reported GL altitude is correct, but open to other suggestions if you feel there is a better/different way to do this. I don't want to assume that a rarely used node library is behaving according to spec. Particularly because our use case requires that we have absolute trust in the library we use.

**Comment by stefwalter** [comment]
@ketan I'll be doing volbiv for a couple days. I haven't polished and completed all corners of this yet, but all the functionality is here. Hope to get back to this soon.

**Comment by stefwalter** [comment]
Rebased to remove merge conflicts

**Comment by ketan** [comment]
This change is now live. 

/cc @cyberorg

**Pull request merged**
